# Generated by Django 5.0.7 on 2024-08-08 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventInfo",
            fields=[
                ("event_name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("event_description", models.TextField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="booking_app.discount",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="booking_app.roomitem",
                    ),
                ),
            ],
        ),
    ]
