# Generated by Django 5.0.7 on 2024-08-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0004_remove_address_user_useraddress_user_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
