# Generated by Django 5.0.7 on 2024-08-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0005_booking_stripe_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatesBooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_booked",
                        to="booking_app.booking",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_booked",
                        to="booking_app.roomitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["room", "check_in", "check_out"],
                        name="booking_app_room_id_d11ead_idx",
                    )
                ],
                "unique_together": {("room", "check_in", "check_out")},
            },
        ),
    ]
