# Generated by Django 5.0.7 on 2024-08-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0006_datesbooked"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booked_rooms",
                to="booking_app.roomitem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roombooked",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_bookings",
                to="booking_app.roomitem",
            ),
        ),
    ]
