# Generated by Django 5.0.7 on 2024-08-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0007_booking_room_alter_roombooked_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booked_rooms",
                to="booking_app.roomitem",
            ),
        ),
    ]
